## Stock Sentiment Analysis using News Headlines.
#About the problem and the dataset used.

The data set in consideration is a combination of the world news and stock price shifts.
Data ranges from 2008 to 2016 and the data from 2000 to 2008 was scrapped from Yahoo finance.
There are 25 columns of top news headlines for each day in the data frame.
Class 1- the stock price increased.
Class 0- the stock price stayed the same or decreased.
About the approach.

Used TF-IDF and Bag of Words for extracting featues from the headlines.
Used Random Forest Classifier, Multinational Naive Bayes and Passive Aggressive Classifier for analysis.

In [285]:
#Importing required library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [286]:
df=pd.read_csv('Data.csv', encoding="ISO-8859-1")

In [287]:
df.head()

Date  Label                                               Top1  \
0  2000-01-03      0  A 'hindrance to operations': extracts from the...   
1  2000-01-04      0                                          Scorecard   
2  2000-01-05      0                  Coventry caught on counter by Flo   
3  2000-01-06      1                      Pilgrim knows how to progress   
4  2000-01-07      1                               Hitches and Horlocks   

                                 Top2  \
0                           Scorecard   
1                 The best lake scene   
2  United's rivals on the road to Rio   
3                 Thatcher facing ban   
4      Beckham off but United survive   

                                            Top3  \
0                Hughes' instant hit buoys Blues   
1                  Leader: German sleaze inquiry   
2  Thatcher issues defence before trial by video   
3        McIlroy calls for Irish fighting spirit   
4                        Breast cancer screening   

                                            Top4  \
0       Jack gets his skates on at ice-cold Alex   
1                                  Cheerio, boyo   
2  Police help Smith lay down the law at Everton   
3                Leicester bin stadium blueprint   
4                                    Alan Parker   

                                          Top5  \
0       Chaos as Maracana builds up for United   
1                     The main recommendations   
2  Tale of Trautmann bears two more retellings   
3               United braced for Mexican wave   
4      Guardian readers: are you all whingers?   

                                                Top6  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees?   
2                                England on the rack   
3  Auntie back in fashion, even if the dress look...   
4                                   Hollywood Beyond   

                                              Top7  \
0                 Hungry Spurs sense rich pickings   
1                           Has Cubie killed fees?   
2  Pakistan retaliate with call for video of Walsh   
3                    Shoaib appeal goes to the top   
4                               Ashes and diamonds   

                                                Top8  ...  \
0                  Gunners so wide of an easy target  ...   
1                             Has Cubie killed fees?  ...   
2               Cullinan continues his Cape monopoly  ...   
3  Hussain hurt by 'shambles' but lays blame on e...  ...   
4                   Whingers - a formidable minority  ...   

                                               Top16  \
0           Flintoff injury piles on woe for England   
1                               On the critical list   
2                        South Melbourne (Australia)   
3  Putin admits Yeltsin quit to give him a head s...   
4                             Most everywhere:  UDIs   

                                               Top17  \
0  Hunters threaten Jospin with new battle of the...   
1                          The timing of their lives   
2                                    Necaxa (Mexico)   
3         BBC worst hit as digital TV begins to bite   
4                       Most wanted:  Chloe lunettes   

                                            Top18  \
0             Kohl's successor drawn into scandal   
1                                     Dear doctor   
2                             Real Madrid (Spain)   
3                     How much can you pay for...   
4  Return of the cane 'completely off the agenda'   

                                               Top19  \
0               The difference between men and women   
1  Irish court halts IRA man's extradition to Nor...   
2                          Raja Casablanca (Morocco)   
3                                 Christmas glitches   
4                   From Sleepy Hollow to Greeneland   

                         

In [288]:
df.columns

Index(['Date', 'Label', 'Top1', 'Top2', 'Top3', 'Top4', 'Top5', 'Top6', 'Top7',
       'Top8', 'Top9', 'Top10', 'Top11', 'Top12', 'Top13', 'Top14', 'Top15',
       'Top16', 'Top17', 'Top18', 'Top19', 'Top20', 'Top21', 'Top22', 'Top23',
       'Top24', 'Top25'],
      dtype='object')

In [289]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4101 entries, 0 to 4100
Data columns (total 27 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Date    4101 non-null   object
 1   Label   4101 non-null   int64 
 2   Top1    4101 non-null   object
 3   Top2    4101 non-null   object
 4   Top3    4101 non-null   object
 5   Top4    4101 non-null   object
 6   Top5    4101 non-null   object
 7   Top6    4101 non-null   object
 8   Top7    4101 non-null   object
 9   Top8    4101 non-null   object
 10  Top9    4101 non-null   object
 11  Top10   4101 non-null   object
 12  Top11   4101 non-null   object
 13  Top12   4101 non-null   object
 14  Top13   4101 non-null   object
 15  Top14   4101 non-null   object
 16  Top15   4101 non-null   object
 17  Top16   4101 non-null   object
 18  Top17   4101 non-null   object
 19  Top18   4101 non-null   object
 20  Top19   4101 non-null   object
 21  Top20   4101 non-null   object
 22  Top21   4101 non-null   

In [309]:
df["Date"].dtypes

dtype('O')

In [310]:
df["Date"][0]

'2000-01-03'

In [311]:
train=df[df['Date']<'20150101']
test=df[df['Date']>'20141231']
train.shape


(3975, 27)

In [312]:
train['Top1'][0]

"A 'hindrance to operations': extracts from the leaked reports"

In [313]:
#Removing punctuations 
train_data=train.iloc[:,2:27]
train_data.replace("[^a-zA-Z]", " ",regex=True, inplace=True)

In [314]:
test_data = test.iloc[:,2:27]
test_data.replace("[^a-zA-Z]", " ",regex=True, inplace=True)

In [315]:
train_data['Top1'][0]

'A  hindrance to operations   extracts from the leaked reports'

In [316]:
train_data.columns

Index(['Top1', 'Top2', 'Top3', 'Top4', 'Top5', 'Top6', 'Top7', 'Top8', 'Top9',
       'Top10', 'Top11', 'Top12', 'Top13', 'Top14', 'Top15', 'Top16', 'Top17',
       'Top18', 'Top19', 'Top20', 'Top21', 'Top22', 'Top23', 'Top24', 'Top25'],
      dtype='object')

In [317]:
for col in train_data.columns:
    train_data[col] = train_data[col].str.lower()
train_data.head()

Top1  \
0  a  hindrance to operations   extracts from the...   
1                                          scorecard   
2                  coventry caught on counter by flo   
3                      pilgrim knows how to progress   
4                               hitches and horlocks   

                                 Top2  \
0                           scorecard   
1                 the best lake scene   
2  united s rivals on the road to rio   
3                 thatcher facing ban   
4      beckham off but united survive   

                                            Top3  \
0                hughes  instant hit buoys blues   
1                  leader  german sleaze inquiry   
2  thatcher issues defence before trial by video   
3        mcilroy calls for irish fighting spirit   
4                        breast cancer screening   

                                            Top4  \
0       jack gets his skates on at ice cold alex   
1                                  cheerio  boyo   
2  police help smith lay down the law at everton   
3                leicester bin stadium blueprint   
4                                    alan parker   

                                          Top5  \
0       chaos as maracana builds up for united   
1                     the main recommendations   
2  tale of trautmann bears two more retellings   
3               united braced for mexican wave   
4      guardian readers  are you all whingers    

                                                Top6  \
0  depleted leicester prevail as elliott spoils e...   
1                             has cubie killed fees    
2                                england on the rack   
3  auntie back in fashion  even if the dress look...   
4                                   hollywood beyond   

                                              Top7  \
0                 hungry spurs sense rich pickings   
1                           has cubie killed fees    
2  pakistan retaliate with call for video of walsh   
3                    shoaib appeal goes to the top   
4                               ashes and diamonds   

                                                Top8  \
0                  gunners so wide of an easy target   
1                             has cubie killed fees    
2               cullinan continues his cape monopoly   
3  hussain hurt by  shambles  but lays blame on e...   
4                   whingers   a formidable minority   

                                                Top9  \
0      derby raise a glass to strupar s debut double   
1  hopkins  furious  at foster s lack of hannibal...   
2             mcgrath puts india out of their misery   
3                      england s decade of disasters   
4                             alan parker   part two   

                                      Top10  ...  \
0  southgate strikes  leeds pay the penalty  ...   
1                    has cubie killed fees   ...   
2            blair witch bandwagon rolls on  ...   
3      revenge is sweet for jubilant cronje  ...   
4                 thuggery  toxins and ties  ...   

                                               Top16  \
0           flintoff injury piles on woe for england   
1                               on the critical list   
2                        south melbourne  australia    
3  putin admits yeltsin quit to give him a head s...   
4                             most everywhere   udis   

                                               Top17  \
0  hunters threaten jospin with new battle of the...   
1                          the timing of their lives   
2                                    necaxa  mexico    
3         bbc worst hit as digital tv begins to bite   
4                       most wanted   chloe lunettes   

                                            Top18  \
0             kohl s successor drawn into scandal   
1                                     dear doctor   
2                             real madrid  spain    
3 

In [319]:
len(train_data.index)

3975

In [320]:
" ".join(str(x) for x in train_data.iloc[1,0:25])

'scorecard the best lake scene leader  german sleaze inquiry cheerio  boyo the main recommendations has cubie killed fees  has cubie killed fees  has cubie killed fees  hopkins  furious  at foster s lack of hannibal appetite has cubie killed fees  a tale of two tails i say what i like and i like what i say elbows  eyes and nipples task force to assess risk of asteroid collision how i found myself at last on the critical list the timing of their lives dear doctor irish court halts ira man s extradition to northern ireland burundi peace initiative fades after rebels reject mandela as mediator pe points the way forward to the ecb campaigners keep up pressure on nazi war crimes suspect jane ratcliffe yet more things you wouldn t know without the movies millennium bug fails to bite'

In [322]:
train_headlines = []
for row in range(0,len(train_data.index)):
    train_headlines.append("".join(str(x) for x in train_data.iloc[row,0:25]))

In [323]:
test_headlines = []
for row in range(0,len(test_data.index)):
    test_headlines.append("".join(str(x) for x in test_data.iloc[row,0:25]))

# TF-IDF

In [423]:
from sklearn.feature_extraction.text  import TfidfVectorizer

In [424]:
TfIDf = TfidfVectorizer(ngram_range=(2,2))
train_df = TfIDf.fit_transform(train_headlines)

In [445]:
test_df = TfIDf.transform(test_headlines)

# MultinomialNB

In [342]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()
nb.fit(train_df,train['Label'])

MultinomialNB()

In [344]:
predictions = nb.predict(test_df)

In [336]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [345]:
matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)

[[130  56]
 [  0 192]]
0.8518518518518519
              precision    recall  f1-score   support

           0       1.00      0.70      0.82       186
           1       0.77      1.00      0.87       192

    accuracy                           0.85       378
   macro avg       0.89      0.85      0.85       378
weighted avg       0.89      0.85      0.85       378



# RandomForestClassifier

In [325]:
from sklearn.ensemble import RandomForestClassifier

In [328]:
RFModel =RandomForestClassifier(n_estimators=200,criterion='entropy')
RFModel.fit(train_df,train['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [466]:
pred = randomclassifier.predict(test_df1)
pred

array([1], dtype=int64)

In [337]:
cm = confusion_matrix(test['Label'],pred)
cm

array([[147,  39],
       [ 18, 174]], dtype=int64)

In [338]:
score = accuracy_score(test['Label'],pred)
score

0.8492063492063492

In [341]:
cr = classification_report(test['Label'],pred)
print(cr)

              precision    recall  f1-score   support

           0       0.89      0.79      0.84       186
           1       0.82      0.91      0.86       192

    accuracy                           0.85       378
   macro avg       0.85      0.85      0.85       378
weighted avg       0.85      0.85      0.85       378



# PassiveAggressiveClassifier

In [449]:
from sklearn.linear_model import PassiveAggressiveClassifier
pa = PassiveAggressiveClassifier()
pa.fit(train_df,train['Label'])

PassiveAggressiveClassifier()

In [450]:
predictions = pa.predict(test_df)
pred = pa.predict(test_df1)
pred

array([0], dtype=int64)

In [351]:
matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)


[[154  32]
 [ 25 167]]
0.8492063492063492
              precision    recall  f1-score   support

           0       0.86      0.83      0.84       186
           1       0.84      0.87      0.85       192

    accuracy                           0.85       378
   macro avg       0.85      0.85      0.85       378
weighted avg       0.85      0.85      0.85       378



# Using bag of words

In [363]:
from sklearn.feature_extraction.text import CountVectorizer
#implement bag of words
bow=CountVectorizer(ngram_range=(2,2))
train_df=bow.fit_transform(train_headlines)
test_df = bow.transform(test_headlines)

# MultinomialNB using Bag of words

In [364]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()
nb.fit(train_df,train['Label'])

predictions = nb.predict(test_df)
matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)


[[140  46]
 [  9 183]]
0.8544973544973545
              precision    recall  f1-score   support

           0       0.94      0.75      0.84       186
           1       0.80      0.95      0.87       192

    accuracy                           0.85       378
   macro avg       0.87      0.85      0.85       378
weighted avg       0.87      0.85      0.85       378



# RandomForestClassifier using Bag of words

In [365]:
# implement RandomForest Classifier
randomclassifier=RandomForestClassifier(n_estimators=200,criterion='entropy')
randomclassifier.fit(train_df,train['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [366]:
predictions = randomclassifier.predict(test_df)
matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)

[[142  44]
 [ 12 180]]
0.8518518518518519
              precision    recall  f1-score   support

           0       0.92      0.76      0.84       186
           1       0.80      0.94      0.87       192

    accuracy                           0.85       378
   macro avg       0.86      0.85      0.85       378
weighted avg       0.86      0.85      0.85       378



# PassiveAggressiveClassifier using Bag of Words

In [368]:
from sklearn.linear_model import PassiveAggressiveClassifier
pa = PassiveAggressiveClassifier()
pa.fit(train_df,train['Label'])

predictions = pa.predict(test_df)
matrix=confusion_matrix(test['Label'],predictions)
print(matrix)
score=accuracy_score(test['Label'],predictions)
print(score)
report=classification_report(test['Label'],predictions)
print(report)


[[160  26]
 [ 24 168]]
0.8677248677248677
              precision    recall  f1-score   support

           0       0.87      0.86      0.86       186
           1       0.87      0.88      0.87       192

    accuracy                           0.87       378
   macro avg       0.87      0.87      0.87       378
weighted avg       0.87      0.87      0.87       378



# Creating a PipeLine

In [369]:
from sklearn.pipeline import Pipeline

In [493]:
RandomForestPipeLine = Pipeline([('Scale' , TfidfVectorizer(ngram_range=(2,2))),('model1', RandomForestClassifier())])

In [494]:
MultinomialNBPipeLine = Pipeline([('Scale' , TfidfVectorizer(ngram_range=(2,2))),('model1', MultinomialNB())])

In [495]:
PassiveAggressiveClassifierPipeLine = Pipeline([('Scale' , TfidfVectorizer(ngram_range=(2,2))),('model1', PassiveAggressiveClassifier())])

In [496]:
myPipeLine = [RandomForestPipeLine,MultinomialNBPipeLine,PassiveAggressiveClassifierPipeLine]

In [497]:
PipeLineDict = {0:"Random Forest", 1:"MultinomialNB", 2 : "PassiveAggressive"}

In [498]:
for pipe in myPipeLine:
    pipe.fit(train_headlines,train['Label'])

In [499]:
pred = []
for pipe in myPipeLine:
    pred.append(pipe.predict(test_headlines))

In [503]:
#Accuracy of the pipeline
for i, model in enumerate(myPipeLine):
    print("{} Test Accuracy : {}".format(PipeLineDict[i], model.score(test_headlines,test['Label'])))
   

Random Forest Test Accuracy : 0.843915343915344
MultinomialNB Test Accuracy : 0.8518518518518519
PassiveAggressive Test Accuracy : 0.8544973544973545
